services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_APP: root:app
      FLASK_HOST: ${FLASK_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    ports:
      - ${FLASK_PORT}:${FLASK_PORT}
    volumes:
      - .:/app
    depends_on:
      - database
    tty: true
    stdin_open: true
    command: python root.py
  database:
    image: postgres:16.3
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
